// Local names that don't appear in the city's official boundary files, mapped to
// the neighborhood polygon they sit inside. This list is editorial rather than
// official - it exists so that searching for "Pilsen" or "Bronzeville" finds the
// right patch of the map, and so the app can show the names people actually use.
window.LOCAL_NAMES = {
  "Lower West Side": ["Pilsen", "Heart of Chicago"],
  "New City": ["Back of the Yards", "Canaryville"],
  "Douglas": ["Bronzeville"],
  "Grand Boulevard": ["Bronzeville"],
  "North Center": ["Roscoe Village", "St. Ben's"],
  "Lincoln Square": ["Ravenswood", "Bowmanville", "Budlong Woods"],
  "Irving Park": ["Old Irving Park", "The Villa", "Kilbourn Park"],
  "Portage Park": ["Six Corners"],
  "West Ridge": ["West Rogers Park", "Peterson Park"],
  "Near South Side": ["South Loop", "Prairie District"],
  "West Town": ["River West", "Noble Square", "Smith Park"],
  "Chicago Lawn": ["Marquette Park", "Lithuanian Plaza"],
  "North Lawndale": ["K-Town", "Douglas Park"],
  "South Lawndale": ["Little Village", "La Villita"],
  "Calumet Heights": ["Pill Hill"],
  "Washington Heights": ["Longwood Manor", "Brainerd"],
  "Ashburn": ["Wrightwood", "Scottsdale"],
  "Auburn Gresham": ["Gresham"],
  "Avondale": ["Kosciuszko Park", "Polish Village"],
  "Belmont Cragin": ["Hanson Park"],
  "Norwood Park": ["Union Ridge", "Old Norwood Park"],
  "Forest Glen": ["Sauganash", "Edgebrook", "Wildwood"],
  "Sauganash / Forest Glen": ["Edgebrook", "Wildwood", "Hollywood Park"],
  "Near North Side": ["Goose Island", "Cabrini", "River North", "Gold Coast"],
  "Lake View": ["Wrigleyville", "Northalsted", "Lakeview East", "Southport Corridor"],
  "Uptown": ["Buena Park", "Sheridan Park", "Margate Park"],
  "Edgewater": ["Andersonville", "Edgewater Glen", "Magnolia Glen"],
  "South Shore": ["Jackson Park Highlands"],
  "Roseland": ["Fernwood", "Rosemoor"],
  "West Pullman": ["Sheldon Heights"],
  "Morgan Park": ["Kennedy Park", "Beverly Woods"],
  "Garfield Ridge": ["Vittum Park", "Sleepy Hollow"],
  "Archer Heights": ["Le Claire Courts"],
  "Hyde Park": ["East Hyde Park"],
  "Woodlawn": ["West Woodlawn"],
  "Humboldt Park": ["Paseo Boricua"],
  "Logan Square": ["Palmer Square", "Bucktown"],
  "Near West Side": ["West Loop", "Greektown", "Little Italy", "Tri-Taylor"],
  "Armour Square": ["Chinatown"],
  "Englewood": ["Hamilton Park"],
  "Greater Grand Crossing": ["Park Manor", "Grand Crossing"],
  "Dunning": ["Schorsch Village", "Belmont Heights"],
};
